# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_JxE_f099ytk6XydLivgbWmizLpTSDE
"""

#import library / 'as' is delcaring about using name is behind of 'as'
import numpy as np

"""# practicing numpy"""

import pandas as pd

a = [1,2,3,4,5,6]

b = np.array(a)

print(a)
print(b)

print(type(a))
print(type(b))

b.reshape(2,3)

b.reshape(-1,2)

b.reshape(2,-1)

"""# Practicing Pandas"""

ser1 = pd.Series([1,2,3,4],['오현고','대기고','일고','제주대'])

ser2 = pd.Series([1,2,3,4],['오현고','대기고','일고','제주대'])

ser1 + ser2

np.random.seed(10)  #seed는 랜덤한 값이 같게 나오게 해줌
value = np.random.randn(5,4) #random.randn 랜덤하게 수를 만들어 준다.
#이때 5행 4열로 만든다는 의미

df = pd.DataFrame(value,[1,2,3,4,5],['A','B','C','D'])

df['A']

df[['A','B']]

df.loc[3]

df.iloc[0] #iloc은 인덱스의 순서로 가져온다

df[df>0]['B']

df[(df['B']>0) & (df['D']>0)]

df.drop('D',axis=1)

df

df.drop('D',axis=1,inplace=True)

df

df['D'] = None

df

a = [1,2,3,4,5]

df['D'] = a

df

data = pd.DataFrame({'highschool':['오현고','대기고','대기고','대기고','중앙고','오현고'],'person': ['person1','person2','person3','person4','person5','person6']})

data['number'] = 1

data

data.groupby('highschool').sum()

data.groupby(['person','highschool']).sum()

data.groupby(['highschool','person']).sum()

"""# Practicing MATPLOTLIB"""

import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

x = np.random.randn(5)

x

x = np.linspace(0,5,11)
y = x**2

x

y

plt.plot(x,y)
plt.show()

plt.plot(x,y)
plt.xlabel('X label')
plt.ylabel('Y label')
plt.title('title')
plt.show()

plt.subplot(1,2,1) #일행 이열에 첫번째 그림을 그리겠다
plt.plot(x,y,'r')

plt.subplot(1,2,2) #일행 이열에 두번째 그림을 그리겠다
plt.plot(y,x,'--')

fig,axes = plt.subplots(nrows=4,ncols=1)
axes[0].plot(x,y)
axes[0].set_xlabel("X_label 1")
axes[1].plot(y,x)
axes[1].set_xlabel("X_label 2")
axes[2].plot(x,y)
axes[3].plot(y,x)
plt.tight_layout()
plt.show()

fig = plt.figure()
axes1 = fig.add_axes([0.1,0.1,0.8,0.8])
axes2 = fig.add_axes([0.5,0.5,0.4,0.2])
plt.show()

plt.scatter(x,y)

